name: Update Random Quote

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  update-quote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Extract and Update Random Quote
        run: |
          #!/usr/bin/env python3
          import random

          README_FILE = "README.md"
          START_MARKER = "<!-- QUOTES_START -->"
          END_MARKER = "<!-- QUOTES_END -->"

          with open(README_FILE, "r", encoding="utf-8") as file:
              lines = file.readlines()

          start_index = lines.index(START_MARKER + "\n") + 1
          end_index = lines.index(END_MARKER + "\n")

          quotes = [line.strip() for line in lines[start_index:end_index] if line.strip()]
          random_quote = random.choice(quotes)

          with open(README_FILE, "w", encoding="utf-8") as file:
              inside_quote_section = False
              for line in lines:
                  if line.strip() == START_MARKER:
                      inside_quote_section = True
                      file.write(line)
                      file.write("\n> " + random_quote + "\n\n")  # Format as a quote
                  elif line.strip() == END_MARKER:
                      inside_quote_section = False
                      file.write(line)
                  elif not inside_quote_section:
                      file.write(line)

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated daily random quote" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
